apiVersion: v1
kind: Service
metadata:
  name: {{ include "htwkarte.name" . }}
  labels:
    {{- include "htwkarte.labels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "htwkarte.selectorLabels" . | nindent 4 }}
