stages:
  - build
  - package
  - deploy

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    COMMIT_TAG: "latest"
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - |
      docker build \
      --pull \
      --build-arg "PROJECT_URL=$PROJECT_URL" \
      -t "$CI_REGISTRY_IMAGE:$COMMIT_TAG" \
      --target prod \
      .
    - docker push "$CI_REGISTRY_IMAGE:$COMMIT_TAG"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

package_helm_chart:
  stage: package
  image:
    name: alpine/helm:3
    entrypoint: [""]
  variables:
    VALUES_FILE: $CI_PROJECT_DIR/charts/values.yaml
    CHART_FILE: $CI_PROJECT_DIR/charts/Chart.yaml
  before_script:
    - echo "HELM_ARTIFACT_JOB_NAME=$CI_JOB_NAME" >> package.env
  script:
    - echo "Updating deployment URLs and image&tag..."
    - yq e -i '(.hosts.frontend // "default_value") = env(PROJECT_URL)' $VALUES_FILE
    - yq e -i '(.image.repository) = env(CI_REGISTRY_IMAGE)' $VALUES_FILE
    - yq e -i 'explode(.)' "$VALUES_FILE"
    - helm dependency update ./charts
    - helm package ./charts --destination ./
  artifacts:
    paths:
      - "*.tgz"
    reports:
      dotenv: package.env
    expire_in: 1 hour
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

trigger_deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Triggering deploy pipeline ..."
    - |
      curl -X POST \
      -F "token=$CI_DEPLOY_REPO_TRIGGER_TOKEN" \
      -F "ref=$CI_DEPLOY_REPO_REF" \
      -F "variables[UPSTREAM_PROJECT_NAME]=$CI_PROJECT_NAME" \
      -F "variables[UPSTREAM_PROJECT_ID]=$CI_PROJECT_ID" \
      -F "variables[UPSTREAM_COMMIT_REF_NAME]=$CI_COMMIT_REF_NAME" \
      -F "variables[UPSTREAM_HELM_ARTIFACT_JOB_NAME]=$HELM_ARTIFACT_JOB_NAME" \
      -F "variables[UPSTREAM_REGISTRY_PATH]=$CI_REGISTRY_IMAGE" \
      "$CI_API_V4_URL/projects/$CI_DEPLOY_REPO_ID/trigger/pipeline"
    - "echo 'The $CI_PROJECT_NAME can be viewed on: $PROJECT_URL'"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
